/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedProtectedRouteRouteImport } from './routes/(protected)/_protected/route'
import { Route as authAuthLayoutRouteRouteImport } from './routes/(auth)/_authLayout/route'
import { Route as protectedProtectedProfileRouteImport } from './routes/(protected)/_protected/profile'
import { Route as protectedProtectedDashboardRouteImport } from './routes/(protected)/_protected/dashboard'
import { Route as authAuthLayoutSignUpRouteImport } from './routes/(auth)/_authLayout/sign-up'
import { Route as authAuthLayoutLoginRouteImport } from './routes/(auth)/_authLayout/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedRouteRoute = protectedProtectedRouteRouteImport.update({
  id: '/(protected)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutRouteRoute = authAuthLayoutRouteRouteImport.update({
  id: '/(auth)/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProtectedProfileRoute =
  protectedProtectedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => protectedProtectedRouteRoute,
  } as any)
const protectedProtectedDashboardRoute =
  protectedProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedProtectedRouteRoute,
  } as any)
const authAuthLayoutSignUpRoute = authAuthLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)
const authAuthLayoutLoginRoute = authAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLayoutLoginRoute
  '/sign-up': typeof authAuthLayoutSignUpRoute
  '/dashboard': typeof protectedProtectedDashboardRoute
  '/profile': typeof protectedProtectedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLayoutLoginRoute
  '/sign-up': typeof authAuthLayoutSignUpRoute
  '/dashboard': typeof protectedProtectedDashboardRoute
  '/profile': typeof protectedProtectedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_authLayout': typeof authAuthLayoutRouteRouteWithChildren
  '/(protected)/_protected': typeof protectedProtectedRouteRouteWithChildren
  '/(auth)/_authLayout/login': typeof authAuthLayoutLoginRoute
  '/(auth)/_authLayout/sign-up': typeof authAuthLayoutSignUpRoute
  '/(protected)/_protected/dashboard': typeof protectedProtectedDashboardRoute
  '/(protected)/_protected/profile': typeof protectedProtectedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/sign-up' | '/dashboard' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sign-up' | '/dashboard' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_authLayout'
    | '/(protected)/_protected'
    | '/(auth)/_authLayout/login'
    | '/(auth)/_authLayout/sign-up'
    | '/(protected)/_protected/dashboard'
    | '/(protected)/_protected/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthLayoutRouteRoute: typeof authAuthLayoutRouteRouteWithChildren
  protectedProtectedRouteRoute: typeof protectedProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected': {
      id: '/(protected)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_authLayout': {
      id: '/(auth)/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_protected/profile': {
      id: '/(protected)/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedProtectedProfileRouteImport
      parentRoute: typeof protectedProtectedRouteRoute
    }
    '/(protected)/_protected/dashboard': {
      id: '/(protected)/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedProtectedDashboardRouteImport
      parentRoute: typeof protectedProtectedRouteRoute
    }
    '/(auth)/_authLayout/sign-up': {
      id: '/(auth)/_authLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authAuthLayoutSignUpRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
    '/(auth)/_authLayout/login': {
      id: '/(auth)/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLayoutLoginRouteImport
      parentRoute: typeof authAuthLayoutRouteRoute
    }
  }
}

interface authAuthLayoutRouteRouteChildren {
  authAuthLayoutLoginRoute: typeof authAuthLayoutLoginRoute
  authAuthLayoutSignUpRoute: typeof authAuthLayoutSignUpRoute
}

const authAuthLayoutRouteRouteChildren: authAuthLayoutRouteRouteChildren = {
  authAuthLayoutLoginRoute: authAuthLayoutLoginRoute,
  authAuthLayoutSignUpRoute: authAuthLayoutSignUpRoute,
}

const authAuthLayoutRouteRouteWithChildren =
  authAuthLayoutRouteRoute._addFileChildren(authAuthLayoutRouteRouteChildren)

interface protectedProtectedRouteRouteChildren {
  protectedProtectedDashboardRoute: typeof protectedProtectedDashboardRoute
  protectedProtectedProfileRoute: typeof protectedProtectedProfileRoute
}

const protectedProtectedRouteRouteChildren: protectedProtectedRouteRouteChildren =
  {
    protectedProtectedDashboardRoute: protectedProtectedDashboardRoute,
    protectedProtectedProfileRoute: protectedProtectedProfileRoute,
  }

const protectedProtectedRouteRouteWithChildren =
  protectedProtectedRouteRoute._addFileChildren(
    protectedProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthLayoutRouteRoute: authAuthLayoutRouteRouteWithChildren,
  protectedProtectedRouteRoute: protectedProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
